cloudforet-io/api

proto/spaceone/api/inventory/v1/cloud_service_tag.proto
Based on the API documentation, I wrote a CloudServiceTag proto.
=> feat: add proto of cloud service tag

proto/spaceone/api/monitoring/v1/metric.proto
docs: modify comments for API docs
=> docs: modify comments for API docs

proto/spaceone/api/secret/v1/trusted_secret.proto
feat: Add Trusted Secret in Secret
Add TrustedSecert APIs ([#26](https://github.com/cloudforet-io/console/issues/26))
=> feat: Add Trusted Secret in Secret

proto/spaceone/api/secret/v1/secret.proto
fix: modify SecretQuery (trusted_secret_id)
=> fix: modify SecretQuery (trusted_secret_id)

proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/cloud_service_tag.proto
=> feat: add tags_info field in CloudServiceInfo

proto/spaceone/api/identity/v1/service_account.proto
feat: add trusted_service_account_id in UpdateServiceAccountRequest
=> feat: add trusted_service_account_id in UpdateServiceAccountRequest

proto/spaceone/api/cost_analysis/plugin/cost.proto, proto/spaceone/api/cost_analysis/plugin/data_source.proto, proto/spaceone/api/cost_analysis/plugin/job.proto
=> feat: add domain_id to CostAnalysis Plugin APIs

proto/spaceone/api/file_manager/v1/file.proto
=> feat: change request message in file_manager APIs

proto/spaceone/api/file_manager/v1/file.proto
=> feat: change FileScope values

proto/spaceone/api/cost_analysis/v1/job.proto
=> feat: add field to cost_analysis.Job

proto/spaceone/api/core/v1/handler.proto
- Add enum values in authorization scope
=> Add Authorization Scope

proto/spaceone/api/inventory/v1/job.proto, proto/spaceone/api/inventory/v1/job_task.proto
A new method has been added to job, job-task.
- `Job.delete`
- `Job.get`
- `JobTask.delete`
- `JobTask.get`
=> create delete method and get method in job, job_task

proto/spaceone/api/inventory/v1/job.proto, proto/spaceone/api/inventory/v1/job_task.proto
add description of api in job, job_task
=> add description of api in job, job_task

proto/spaceone/api/core/v1/handler.proto
Remove authorization scope
- `DOMAIN_OR_USER`
- `PROJECT_OR_USER`
=> Rollback Authorization Scope

proto/spaceone/api/dashboard/v1/domain_dashboard.proto, proto/spaceone/api/dashboard/v1/project_dashboard.proto
* add viewers field in dashboard service
=> add viewers field in dashboard service

proto/spaceone/api/dashboard/v1/domain_dashboard.proto, proto/spaceone/api/dashboard/v1/project_dashboard.proto
remove user_id field in domain and project dashboard
=> remove user_id field in domain and project dashboard

proto/spaceone/api/dashboard/v1/custom_widget.proto
modify list code in custom widget of dashboard service
=> bugfix: modify list code in custom widget of dashboard service

proto/spaceone/api/cost_analysis/v1/data_source.proto
- add `cost_tag_keys` field to DataSourceInfo
- add `cost_additional_info_keys` field to DataSourceInfo
=> Change Cost Analysis Message

proto/spaceone/api/dashboard/v1/custom_widget.proto, proto/spaceone/api/dashboard/v1/domain_dashboard.proto, proto/spaceone/api/dashboard/v1/project_dashboard.proto
Signed-off-by: seolmin <seolmin@megazone.com>
* change variable name from dashboard_options to dashboard_variables
=> change variable name from dashboard_options to dashboard_variables

proto/spaceone/api/core/v1/query.proto
- add filter_or options to AnalyzeQuery
- add filter_or options to TimeSeriesAnalyzeQuery
=> Change AnalyzeQuery

proto/spaceone/api/repository/v1/plugin.proto
- add enum field for PublicRegistryType in repository APIs
=> feat: add enum field for PublicRegistryType in repository APIs

proto/spaceone/api/plugin/v1/supervisor.proto
- add domain_id field to `Supervisor.list_plugins` API
=> Add Field to Plugin Service

proto/spaceone/api/dashboard/v1/custom_widget.proto, proto/spaceone/api/dashboard/v1/domain_dashboard.proto, proto/spaceone/api/dashboard/v1/project_dashboard.proto
Signed-off-by: seolmin <seolmin@megazone.com>
* change the settings from specific settings type to dict type
* add settings field in CustomWidget
=> change the settings from specific settings type to dict type

proto/spaceone/api/cost_analysis/v1/data_source_rule.proto
Modify `data_source_type` to `rule_type` in DataSourceRule.
This value defines the type for the data source rule, so it's exactly named `rule_type` .
* https://github.com/cloudforet-io/cost-analysis/issues/24
=> Modify data_source_type to rule_type in DataSourceRule

proto/spaceone/api/core/v1/query.proto, proto/spaceone/api/inventory/v1/cloud_service.proto
- add analyze API to inventory.CloudService
- https://github.com/cloudforet-io/inventory/issues/28
=> Add analyze API to inventory.CloudService

proto/spaceone/api/inventory/v1/collector_rule.proto
When Collector collects Cloud Service resources, it performs the function of changing resource data (ex. modifying related Project) through CollectorRules.
* https://github.com/cloudforet-io/inventory/issues/24
=> feat: Add CollectorRule for Inventory

proto/spaceone/api/repository/v2/provider.proto, proto/spaceone/api/repository/v2/remote_repository.proto
new proto file has updated for repository-v2
=> feat: add proto for repository-v2

proto/spaceone/api/repository/v2/provider.proto, proto/spaceone/api/repository/v2/remote_repository.proto
=> fix: fix typo

proto/spaceone/api/repository/v2/provider.proto
=> feat: update SyncMode fields

proto/spaceone/api/repository/v2/remote_repository.proto
Fix typo `RemoteRpository` to `RemoteRepository`
=> fix: fix typo 'RemoteRpository'

proto/spaceone/api/inventory/plugin/collector.proto, proto/spaceone/api/inventory/v1/change_history.proto, proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/cloud_service_type.proto, proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/inventory/v1/collector_rule.proto, proto/spaceone/api/inventory/v1/job.proto, proto/spaceone/api/inventory/v1/job_task.proto, proto/spaceone/api/inventory/v1/note.proto, proto/spaceone/api/inventory/v1/region.proto, proto/spaceone/api/inventory/v1/resource_group.proto
Signed-off-by: ImMin5 <mino@megazone.com>
- modify inventory service http request url at proto file
=> Modify inventory service http request url at proto file

proto/spaceone/api/notification/plugin/notification.proto, proto/spaceone/api/notification/plugin/protocol.proto, proto/spaceone/api/notification/v1/notification.proto, proto/spaceone/api/notification/v1/notification_usage.proto, proto/spaceone/api/notification/v1/project_channel.proto, proto/spaceone/api/notification/v1/protocol.proto, proto/spaceone/api/notification/v1/quota.proto, proto/spaceone/api/notification/v1/user_channel.proto
Signed-off-by: ImMin5 <mino@megazone.com>
- modify `notification` service http request url at proto file
=> Modify notification service http request url at proto file

proto/spaceone/api/repository/v2/provider.proto
We discussed the name of the schema_options field and decided to rename it to capability.
This PR reflects that discussion.
=> feat: modify schema_options to capability

proto/spaceone/api/dashboard/v1/custom_widget.proto, proto/spaceone/api/dashboard/v1/domain_dashboard.proto, proto/spaceone/api/dashboard/v1/project_dashboard.proto
- modify`dashboard` service http request url at proto file
=> Modify dashboard service http request url at proto file

proto/spaceone/api/identity/plugin/auth.proto, proto/spaceone/api/identity/v1/api_key.proto, proto/spaceone/api/identity/v1/authorization.proto, proto/spaceone/api/identity/v1/domain.proto, proto/spaceone/api/identity/v1/domain_owner.proto, proto/spaceone/api/identity/v1/endpoint.proto, proto/spaceone/api/identity/v1/policy.proto, proto/spaceone/api/identity/v1/project.proto, proto/spaceone/api/identity/v1/project_group.proto, proto/spaceone/api/identity/v1/provider.proto, proto/spaceone/api/identity/v1/role.proto, proto/spaceone/api/identity/v1/role_binding.proto, proto/spaceone/api/identity/v1/service_account.proto, proto/spaceone/api/identity/v1/token.proto, proto/spaceone/api/identity/v1/user.proto
Signed-off-by: ImMin5 <mino@megazone.com>
- modify identity service http request url at proto file
=> Modify identity service http request url at proto file

proto/spaceone/api/repository/v2/provider.proto
add remote_repository_name message field for list query
=> feat: add remote_repository_name field for query

proto/spaceone/api/repository/v2/schema.proto
**INFO: This PR will be merged into `feature-repo-v2-schema` branch in upstream**
protobuf of schema has been implemented.
- API document : [link](https://docs.google.com/spreadsheets/d/1BCC-EgErEwZwkn9L6byoKB2yCSYzrAaQJipgcn-NZ1g/edit#gid=845273752)
- QUEST issue : [link](https://pyengine.atlassian.net/jira/software/projects/QUEST/boards/34?selectedIssue=QUEST-46)
=> feat: implement protobuf for schema resource

proto/spaceone/api/repository/v2/schema.proto
Oops.. I was missing sync method of schema interface.
This PR fix that issue.
=> Feature repo v2 schema

proto/spaceone/api/identity/v1/user.proto
- add email_verified filed at UserInfo of identity.User 
-  add `email_verified` field
=> Add email_verified filed at UserInfo of identity.User 

proto/spaceone/api/identity/v1/user.proto
- modify message and rpc of identity.User
- add confirm_email rpc and message
- deleted VerifyEmail message
- modify CreateUserRequest message
=> feat: modify message and rpc of identity.User

proto/spaceone/api/identity/v1/user.proto
- modify ConfirmEmailRequest field name
- `verify_token` -> `verify_code`
=> Modify ConfirmEmailRequest field name

proto/spaceone/api/identity/v1/user.proto
=> Modify verify_email return message and field

proto/spaceone/api/identity/v1/user.proto
- remove email field at UserRequest and add VerifyEmailRequest
=> Remove email field at UserRequest and add VerifyEmailRequest

proto/spaceone/api/identity/v1/user.proto
- add reset_password field at UpdateUserRequest
=> Add reset_password field at UpdateUserRequest

proto/spaceone/api/repository/v2/common.proto, proto/spaceone/api/repository/v2/provider.proto, proto/spaceone/api/repository/v2/remote_repository.proto, proto/spaceone/api/repository/v2/schema.proto
- A new Protobuf(common.proto) has been added
- syncOptions message has been replaced to common.proto
- This message is referenced by both provider and schema 
- schema field in provider.proto has been renamed to providerSchema to avoid conflict
- fix typo
=> improve,fix: add common_info and fix wrong message fields

proto/spaceone/api/repository/v2/provider.proto, proto/spaceone/api/repository/v2/schema.proto
fix wrong data type of query field of Query Messsage in provider,schema.proto
=> fix: wrong data type of query field

proto/spaceone/api/identity/v1/user.proto
=> Commit for commenting

proto/spaceone/api/identity/v1/user.proto
=> Remove comment

.gitignore
Signed-off-by: Minho Kim <mino@megazone.com>
- Remove dist directory in .gitignore file
=> Remove dist directory in .gitignore file

.github/workflows/dispatch_release.yaml, proto/spaceone/api/identity/v1/user.proto
=> Fix typo at identity.User

Makefile, bin/build.py, proto/spaceone/api/board/v1/board.proto, proto/spaceone/api/board/v1/post.proto, proto/spaceone/api/cost_analysis/plugin/cost.proto, proto/spaceone/api/cost_analysis/plugin/data_source.proto, proto/spaceone/api/cost_analysis/plugin/job.proto, proto/spaceone/api/cost_analysis/v1/budget.proto, proto/spaceone/api/cost_analysis/v1/budget_usage.proto, proto/spaceone/api/cost_analysis/v1/cost.proto, proto/spaceone/api/cost_analysis/v1/cost_query_set.proto, proto/spaceone/api/cost_analysis/v1/custom_widget.proto, proto/spaceone/api/cost_analysis/v1/data_source.proto, proto/spaceone/api/cost_analysis/v1/data_source_rule.proto, proto/spaceone/api/cost_analysis/v1/exchange_rate.proto, proto/spaceone/api/cost_analysis/v1/job.proto, proto/spaceone/api/cost_analysis/v1/job_task.proto, proto/spaceone/api/cost_analysis/v1/public_dashboard.proto, proto/spaceone/api/cost_analysis/v1/schedule.proto, proto/spaceone/api/cost_analysis/v1/user_dashboard.proto
- modify commet at board and cost_analysis
=> Modify commet at board and cost_analysis

proto/spaceone/api/board/v1/board.proto, proto/spaceone/api/inventory/plugin/collector.proto, proto/spaceone/api/inventory/v1/change_history.proto, proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/cloud_service_type.proto, proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/inventory/v1/collector_rule.proto, proto/spaceone/api/inventory/v1/job.proto, proto/spaceone/api/inventory/v1/job_task.proto, proto/spaceone/api/inventory/v1/note.proto, proto/spaceone/api/inventory/v1/region.proto, proto/spaceone/api/inventory/v1/resource_group.proto
- modify comment at inventory proto files
=> Modify comment at inventory proto files

proto/spaceone/api/config/v1/domain_config.proto, proto/spaceone/api/config/v1/user_config.proto
- modify comment at core proto files
=> Modify comment at core proto files

proto/spaceone/api/dashboard/v1/custom_widget.proto, proto/spaceone/api/dashboard/v1/domain_dashboard.proto, proto/spaceone/api/dashboard/v1/project_dashboard.proto
- modify comment at dashboard proto files
=> Modify comment at dashboard proto files

proto/spaceone/api/file_manager/v1/file.proto
- modify comment at file_manager proto files
=> Modify comment at file_manager proto files

proto/spaceone/api/identity/plugin/auth.proto, proto/spaceone/api/identity/v1/api_key.proto, proto/spaceone/api/identity/v1/authorization.proto, proto/spaceone/api/identity/v1/domain.proto, proto/spaceone/api/identity/v1/domain_owner.proto, proto/spaceone/api/identity/v1/endpoint.proto, proto/spaceone/api/identity/v1/policy.proto, proto/spaceone/api/identity/v1/project.proto, proto/spaceone/api/identity/v1/project_group.proto, proto/spaceone/api/identity/v1/provider.proto, proto/spaceone/api/identity/v1/role.proto, proto/spaceone/api/identity/v1/role_binding.proto, proto/spaceone/api/identity/v1/service_account.proto, proto/spaceone/api/identity/v1/token.proto, proto/spaceone/api/identity/v1/user.proto
- modify comment at identity proto files
=> Modify comment at identity proto files

proto/spaceone/api/notification/plugin/notification.proto, proto/spaceone/api/notification/plugin/protocol.proto, proto/spaceone/api/notification/v1/notification.proto, proto/spaceone/api/notification/v1/notification_usage.proto, proto/spaceone/api/notification/v1/project_channel.proto, proto/spaceone/api/notification/v1/protocol.proto, proto/spaceone/api/notification/v1/quota.proto, proto/spaceone/api/notification/v1/user_channel.proto, proto/spaceone/api/plugin/v1/plugin.proto, proto/spaceone/api/plugin/v1/supervisor.proto, proto/spaceone/api/repository/v1/plugin.proto, proto/spaceone/api/repository/v1/policy.proto, proto/spaceone/api/repository/v1/repository.proto, proto/spaceone/api/repository/v1/schema.proto, proto/spaceone/api/repository/v2/provider.proto, proto/spaceone/api/repository/v2/remote_repository.proto, proto/spaceone/api/repository/v2/schema.proto, proto/spaceone/api/sample/v1/helloworld.proto, proto/spaceone/api/secret/v1/secret.proto, proto/spaceone/api/secret/v1/secret_group.proto, proto/spaceone/api/secret/v1/trusted_secret.proto, proto/spaceone/api/statistics/plugin/storage.proto, proto/spaceone/api/statistics/v1/history.proto, proto/spaceone/api/statistics/v1/resource.proto, proto/spaceone/api/statistics/v1/schedule.proto, proto/spaceone/api/statistics/v1/storage.proto
- modify repository, statistics, notification and secret
=> Modify comment at repository, statistics, notification and secret proto files

proto/spaceone/api/cost_analysis/plugin/cost.proto
=> feat: Add usage_unit in Cost Analysis Plugin

proto/spaceone/api/cost_analysis/v1/cost.proto
=> feat: Add usage_unit in Cost Analysis

proto/spaceone/api/cost_analysis/plugin/cost.proto, proto/spaceone/api/cost_analysis/v1/cost.proto, proto/spaceone/api/inventory/v1/collector.proto
=> feat: recover the resource_group field

proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/plugin/v1/plugin.proto
=> Add get_plugin_metadata

proto/spaceone/api/cost_analysis/v1/cost.proto
fix: typo (resource_type to resource_group)
=> typo (resource_type to resource_group)

proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/cloud_service_query_set.proto, proto/spaceone/api/inventory/v1/cloud_service_stats.proto, proto/spaceone/api/inventory/v1/job.proto
- add cloud service stats APIs
- add analyze API to inventory job resource
=> Add inventory APIs

bin/build.py
- remove grpc gateway build code
=> refactor: remove grpc gateway build code

proto/spaceone/api/plugin/v1/plugin.proto
Add upgrade_mode in get_plugin_metadata request
=> Add upgrade_mode in get_plugin_metadata request

proto/spaceone/api/inventory/v1/cloud_service_query_set.proto, proto/spaceone/api/inventory/v1/cloud_service_stats.proto
- change data type of `unit` in CloudServiceQuerySet
- add `key` field to CloudServiceStats
=> Change Inventory Fields

proto/spaceone/api/inventory/v1/collector.proto
Delete collector.enable/disable. 
Update CreateCollector params
=> Delete collector.enable/disable. update CreateCollector params

proto/spaceone/api/inventory/v1/collector.proto
Add secret_filter in CollectorInfo
=> Add secret_filter in CollectorInfo

proto/spaceone/api/identity/v1/service_account.proto
- add `has_secret` parameter to `identity.ServiceAccount.list` API
=> feat: add has_secret parameter

proto/spaceone/api/identity/v1/service_account.proto
- add `has_secret` parameter to ServiceAccountStatQuery
=> feat: add has_secret parameter to ServiceAccountStatQuery

proto/spaceone/api/repository/v1/repository.proto
- remove unused fields in repository service
- change API examples
=> feat: remove unused fields

bin/build.py, proto/spaceone/api/inventory/v1/cloud_service_query_set.proto
- fix http url at cloud_service_query_set.proto
- modify duplicated http url
=> Fix http url at cloud_service_query_set.proto

proto/spaceone/api/cost_analysis/v1/data_source.proto
- add DeregisterDataSourceRequest message at data_source.proto
=> Add DeregisterDataSourceRequest message at data_source.proto

proto/spaceone/api/cost_analysis/v1/data_source.proto
add secret_type, secret_filter in DataSource
=> add secret_type, secret_filter in DataSource

proto/spaceone/api/cost_analysis/v1/data_source.proto
Add secret_filter, in UpdateDataSource
=> Add secret_filter, in UpdateDataSource

proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/inventory/v1/job.proto
update Job, Collector for inventory
=> feat: update Job, Collector for inventory

proto/spaceone/api/inventory/v1/job.proto
=> update JobStatus Query enum

proto/spaceone/api/inventory/plugin/job.proto
=> Add Inventory Plugin.Job

proto/spaceone/api/inventory/plugin/collector.proto
=> add task_options

proto/spaceone/api/cost_analysis/v1/cost_query_set.proto
- add `data_source_id` field to CostQuerySet APIs
=> feat: add data_source_id field to CostQuerySet APIs

proto/spaceone/api/cost_analysis/v1/budget.proto, proto/spaceone/api/cost_analysis/v1/budget_usage.proto
- add provider_filter to BudgetUsageInfo
=> feat: add provider_filter to BudgetUsageInfo

proto/spaceone/api/cost_analysis/v1/cost.proto
- add `project_group_id` field to CostInfo
=> feat: add project_group_id field to CostInfo

proto/spaceone/api/cost_analysis/v1/cost_query_set.proto
- change field description of CostQuerySetQuery
=> feat: change field description of CostQuerySetQuery

proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/cloud_service_query_set.proto
- remove `resource_group_id` option in CloudServiceQuery
- add `test` API to CloudServiceQuerySet
=> Change Message and Add New API

proto/spaceone/api/inventory/v1/cloud_service_query_set.proto, proto/spaceone/api/inventory/v1/cloud_service_stats.proto
- change fields in CloudServiceQuerySet
- change fields in CloudServiceStats
=> Change Fields in Inventory

proto/spaceone/api/inventory/v1/cloud_service_stats.proto
- change fields in CloudServiceStats
=> feat: change fields in CloudServiceStats

proto/spaceone/api/identity/v1/provider.proto
- add `domain_id` field to ProviderInfo
=> feat: add domain_id field to ProviderInfo

proto/spaceone/api/identity/v1/provider.proto
- add `order` field to Provider APIs
=> feat: add order field to Provider APIs

Dockerfile
- modify Dockerfile ubuntu image version 18.04 -> 20.04
- modify ubuntu image version because of default python version
=> Modify Dockerfile ubuntu image version 18.04 -> 20.04

pkg/pip_requirements.txt
- add package Jinja2 at pip_requirements.txt
=> Add package Jinja2 at pip_requirements.txt

bin/build.py
- fix the issue of repetitive environment builds for each code
=> Fix the issue of repetitive environment builds for each code

proto/spaceone/api/board/v1/board.proto, proto/spaceone/api/cost_analysis/v1/cost_query_set.proto, proto/spaceone/api/identity/v1/authorization.proto, proto/spaceone/api/identity/v1/domain.proto, proto/spaceone/api/identity/v1/domain_owner.proto, proto/spaceone/api/identity/v1/policy.proto, proto/spaceone/api/identity/v1/project_group.proto, proto/spaceone/api/identity/v1/service_account.proto, proto/spaceone/api/identity/v1/user.proto, proto/spaceone/api/monitoring/v1/data_source.proto, proto/spaceone/api/notification/v1/project_channel.proto
- remove some system scope http url from proto files
=> Remove some system scope http url from proto files

proto/spaceone/api/repository/v1/plugin.proto
* Change public ECR to private ECR in plugin proto
=> Change public ECR to private ECR in plugin proto

proto/spaceone/api/plugin/v1/plugin.proto
- fix typo at plugin.proto file of plugin service
=> Fix typo at plugin.proto file of plugin service

proto/spaceone/api/core/v1/query.proto, proto/spaceone/api/inventory/v1/cloud_service.proto
- add export messages to core protobuf
- add `CloudService.export` API
=> Export API

proto/spaceone/api/plugin/v1/plugin.proto, proto/spaceone/api/repository/v1/repository.proto
- remove http url from proto files
=> Remove http url from proto files

proto/spaceone/api/core/v1/query.proto, proto/spaceone/api/inventory/v1/cloud_service.proto
- remove unused message
- change return message of `CloudService.export` API
=> Change Export API

proto/spaceone/api/core/v1/query.proto, proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/cloud_service_query_set.proto, proto/spaceone/api/inventory/v1/cloud_service_report.proto
- rename exportOptions to ExportOption
- add file_format field to CloudServiceExportRequest
- add cloud service report APIs
=> Cloud Service Report API

proto/spaceone/api/inventory/v1/cloud_service_report.proto
- rename updated_at to last_sent_at
=> feat: rename updated_at to last_sent_at

proto/spaceone/api/cost_analysis/plugin/cost.proto
add data filed at CostInfo message
=> Add data filed at CostInfo message

proto/spaceone/api/core/v1/query.proto, proto/spaceone/api/cost_analysis/v1/data_source.proto, proto/spaceone/api/inventory/v1/cloud_service_query_set.proto
- change field name in CloudServiceQuerySetInfo (`keys` -> `data_keys`)
- add `cost_data_keys` field to DataSourceInfo
- add `unwind` and `page` option to ExportQuery
=> Add Message Fields

bin/openapi.py, proto/spaceone/api/cost_analysis/v1/cost.proto, proto/spaceone/api/identity/v1/token.proto, proto/spaceone/api/identity/v1/user.proto
- modify identity.User and identity.Token field for mfa authentication
=> Modify identity.User and identity.Token field for mfa authentication

proto/spaceone/api/identity/v1/token.proto, proto/spaceone/api/identity/v1/user.proto
- Add example code at user.proto and token.proto
=> Add example code at user.proto and token.proto

proto/spaceone/api/identity/v1/user.proto
- modify description at user.proto
=> Modify description at user.proto

proto/spaceone/api/core/v1/query.proto
- change unwind field in query
=> feat: change unwind field in query

proto/spaceone/api/core/v2/handler.proto, proto/spaceone/api/core/v2/plugin.proto, proto/spaceone/api/identity/v2/api_key.proto, proto/spaceone/api/identity/v2/authorization.proto, proto/spaceone/api/identity/v2/domain.proto, proto/spaceone/api/identity/v2/endpoint.proto, proto/spaceone/api/identity/v2/external_auth.proto, proto/spaceone/api/identity/v2/policy.proto, proto/spaceone/api/identity/v2/project.proto, proto/spaceone/api/identity/v2/project_group.proto, proto/spaceone/api/identity/v2/provider.proto, proto/spaceone/api/identity/v2/role.proto, proto/spaceone/api/identity/v2/role_binding.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/token.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/identity/v2/user.proto, proto/spaceone/api/identity/v2/user_group.proto, proto/spaceone/api/identity/v2/workspace.proto
- add all resources proto files for identity v2
=> Add all resources proto files for identity v2

proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/cloud_service_report.proto
- add `timezone` option to cloud service export API
- add `timezone` and `language` options to cloud service export APIs
=> Add timezone and language options to cloud service report APIs

proto/spaceone/api/core/v1/query.proto, proto/spaceone/api/inventory/v1/cloud_service.proto
- add `file_name` option to cloud service export API
- add `title` option to export query
=> Change Parameter in Export API

proto/spaceone/api/inventory/v1/cloud_service_report.proto
- add language field
- add timezone field
=> feat: add language and timezone fields to CloudServiceReportInfo

proto/spaceone/api/identity/v2/service_account.proto
- remove `ServiceAccount.change_project` API
=> feat: remove ServiceAccount.change_project API

proto/spaceone/api/identity/v2/domain.proto, proto/spaceone/api/identity/v2/project.proto
=> Fix typo and remove korean comment

proto/spaceone/api/identity/v2/policy.proto, proto/spaceone/api/identity/v2/role.proto
- change role fields in identity v2
- change policy fields in identity v2
=> feat: change role and policy fields

proto/spaceone/api/identity/v2/role_binding.proto
- add workspace_id field in identity v2
=> feat: add workspace_id field

proto/spaceone/api/identity/v2/role_binding.proto
=> feat: add role_type field

template/openapi/openapi.json.tmpl
- add temporary static version for openapi.json
=> Add temporary static version for openapi.json 

proto/spaceone/api/identity/v2/api_key.proto, proto/spaceone/api/identity/v2/app.proto, proto/spaceone/api/identity/v2/role.proto, proto/spaceone/api/identity/v2/user.proto
=> feat: change fields in identity

proto/spaceone/api/core/v2/handler.proto, proto/spaceone/api/identity/v2/role.proto, proto/spaceone/api/identity/v2/role_binding.proto, proto/spaceone/api/identity/v2/user.proto
=> fix: fix wrong enum values

proto/spaceone/api/identity/v2/api_key.proto, proto/spaceone/api/identity/v2/app.proto, proto/spaceone/api/identity/v2/project.proto, proto/spaceone/api/identity/v2/provider.proto, proto/spaceone/api/identity/v2/schema.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/identity/v2/trusted_service_account.proto, proto/spaceone/api/identity/v2/user.proto, proto/spaceone/api/identity/v2/user_group.proto
=> Change Identity v2 APIs

proto/spaceone/api/identity/v2/policy.proto, proto/spaceone/api/identity/v2/role.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/workspace.proto
- change fields in identity v2
=> feat: change fields in identity v2

proto/spaceone/api/core/v2/handler.proto, proto/spaceone/api/identity/v2/authorization.proto, proto/spaceone/api/identity/v2/domain.proto, proto/spaceone/api/identity/v2/external_auth.proto, proto/spaceone/api/identity/v2/project_group.proto, proto/spaceone/api/identity/v2/provider.proto, proto/spaceone/api/identity/v2/role.proto, proto/spaceone/api/identity/v2/role_binding.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/token.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/identity/v2/user.proto, proto/spaceone/api/identity/v2/workspace.proto
=> feat: change identity v2 apis

proto/spaceone/api/core/v2/handler.proto, proto/spaceone/api/core/v2/query.proto, proto/spaceone/api/identity/v2/api_key.proto, proto/spaceone/api/identity/v2/app.proto, proto/spaceone/api/identity/v2/domain.proto, proto/spaceone/api/identity/v2/endpoint.proto, proto/spaceone/api/identity/v2/project.proto, proto/spaceone/api/identity/v2/project_group.proto, proto/spaceone/api/identity/v2/provider.proto, proto/spaceone/api/identity/v2/role.proto, proto/spaceone/api/identity/v2/role_binding.proto, proto/spaceone/api/identity/v2/schema.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/identity/v2/user.proto, proto/spaceone/api/identity/v2/user_group.proto, proto/spaceone/api/identity/v2/workspace.proto
=> feat: change APIs for identity v2

proto/spaceone/api/identity/v2/domain.proto, proto/spaceone/api/identity/v2/project.proto, proto/spaceone/api/identity/v2/project_group.proto, proto/spaceone/api/identity/v2/provider.proto, proto/spaceone/api/identity/v2/role_binding.proto, proto/spaceone/api/identity/v2/schema.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/identity/v2/user.proto, proto/spaceone/api/identity/v2/user_group.proto, proto/spaceone/api/identity/v2/workspace.proto, proto/spaceone/api/identity/v2/workspace_user.proto
=> chore: change doc string

proto/spaceone/api/identity/v2/user.proto
=> fix: fix wrong field name

proto/spaceone/api/identity/v2/schema.proto
- change field name in Schema API
=> feat: change field name in Schema API

proto/spaceone/api/identity/v2/user.proto
- fix user get_workspaces http url
=> Fix user get_workspaces http url

proto/spaceone/api/board/v1/board.proto, proto/spaceone/api/board/v1/post.proto, proto/spaceone/api/config/v1/domain_config.proto, proto/spaceone/api/config/v1/user_config.proto, proto/spaceone/api/file_manager/v1/file.proto, proto/spaceone/api/file_manager/v1/public_file.proto
* Change variable for SpaceONE 2.0 in Board and File Manager services
=> fix: change variable for SpaceONE 2.0 in Board and File Manager services

proto/spaceone/api/identity/v2/role.proto
=> fix: fix wrong field type

proto/spaceone/api/identity/v2/trusted_account.proto
=> fix: fix wrong message

proto/spaceone/api/identity/v2/token.proto
=> feat: change field in token API

proto/spaceone/api/identity/v2/token.proto
=> fix: fix wrong grant type

proto/spaceone/api/identity/v2/token.proto
- change GrantTokenInfo message
=> feat: change GrantTokenInfo message

proto/spaceone/api/notification/v1/notification.proto, proto/spaceone/api/notification/v1/project_channel.proto, proto/spaceone/api/notification/v1/protocol.proto, proto/spaceone/api/notification/v1/user_channel.proto, proto/spaceone/api/plugin/v1/plugin.proto, proto/spaceone/api/repository/v1/plugin.proto, proto/spaceone/api/repository/v1/repository.proto, proto/spaceone/api/statistics/v1/history.proto, proto/spaceone/api/statistics/v1/resource.proto, proto/spaceone/api/statistics/v1/schedule.proto
- Config
- Statistics
- Repository
- Notification
- Plugin
=> fix: change variables for SpaceONE 2.0

proto/spaceone/api/inventory/v1/change_history.proto, proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/cloud_service_query_set.proto, proto/spaceone/api/inventory/v1/cloud_service_report.proto, proto/spaceone/api/inventory/v1/cloud_service_stats.proto, proto/spaceone/api/inventory/v1/cloud_service_type.proto, proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/inventory/v1/collector_rule.proto, proto/spaceone/api/inventory/v1/job.proto, proto/spaceone/api/inventory/v1/job_task.proto, proto/spaceone/api/inventory/v1/note.proto, proto/spaceone/api/inventory/v1/region.proto
=> fix: change variables for SpaceONE 2.0 in Inventory service

proto/spaceone/api/identity/v2/app.proto, proto/spaceone/api/identity/v2/role_binding.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/secret/v1/secret.proto, proto/spaceone/api/secret/v1/trusted_secret.proto
- remove `resource_group` field in SearchQuery
- change secret protos for identity compatability
=> Change Identity & Secret Protos

proto/spaceone/api/inventory/v1/cloud_service_query_set.proto
- fix wrong message in cloud service query set
=> fix: fix wrong message in cloud service query set

proto/spaceone/api/inventory/v1/collector_rule.proto
- fix wrong message in collector rule
=> fix: fix wrong message in collector rule

proto/spaceone/api/identity/v2/domain.proto, proto/spaceone/api/inventory/v1/cloud_service_query_set.proto, proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/inventory/v1/collector_rule.proto, proto/spaceone/api/inventory/v1/note.proto, proto/spaceone/api/inventory/v1/region.proto, proto/spaceone/api/secret/v1/secret.proto, proto/spaceone/api/secret/v1/trusted_secret.proto
- fix lint
- remove rest option of system API
=> Refactor Proto for SpaceONE 2.0

proto/spaceone/api/monitoring/v1/alert.proto, proto/spaceone/api/monitoring/v1/data_source.proto, proto/spaceone/api/monitoring/v1/event.proto, proto/spaceone/api/monitoring/v1/event_rule.proto, proto/spaceone/api/monitoring/v1/note.proto, proto/spaceone/api/monitoring/v1/project_alert_config.proto, proto/spaceone/api/monitoring/v1/webhook.proto
- change monitoring protos for SpaceONE 2.0
=> feat: change monitoring protos for SpaceONE 2.0

proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/secret/v1/secret.proto, proto/spaceone/api/secret/v1/trusted_secret.proto
- change identity message
- change secret message
=> feat: change identity and secret messages

proto/spaceone/api/secret/v1/secret.proto
- change message in secret service
=> feat: change message in secret service

proto/spaceone/api/identity/v2/workspace.proto
=> feat: add Workspace.check API

proto/spaceone/api/identity/v2/workspace.proto
- change message of `Workspace.check` API
=> feat: change message of Workspace.check API

proto/spaceone/api/identity/v2/app.proto, proto/spaceone/api/identity/v2/role.proto, proto/spaceone/api/identity/v2/role_binding.proto, proto/spaceone/api/identity/v2/system.proto, proto/spaceone/api/identity/v2/token.proto, proto/spaceone/api/identity/v2/user.proto, proto/spaceone/api/identity/v2/workspace_user.proto
=> feat: change identity message

proto/spaceone/api/identity/v2/app.proto
=> feat: add App.check API

proto/spaceone/api/identity/v2/token.proto
- change message of `Token.grant` API
=> feat: change message of Token.grant API

proto/spaceone/api/identity/v2/app.proto
=> feat: remove unused field

proto/spaceone/api/identity/v2/app.proto
- change supported role type in app
=> feat: change supported role type in app

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto
* Create public and private dashboard resources in dashboard service
=> feat: create public and private dashboard resources in dashboard service

proto/spaceone/api/cost_analysis/v1/budget.proto, proto/spaceone/api/cost_analysis/v1/data_source.proto, proto/spaceone/api/cost_analysis/v1/data_source_rule.proto, proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto, proto/spaceone/api/identity/v2/app.proto, proto/spaceone/api/identity/v2/role_binding.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/inventory/v1/cloud_service_query_set.proto, proto/spaceone/api/inventory/v1/cloud_service_report.proto, proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/monitoring/v1/escalation_policy.proto, proto/spaceone/api/secret/v1/secret.proto, proto/spaceone/api/secret/v1/trusted_secret.proto
- add workspace_id field to compound APIs
=> feat: add workspace_id field to compound APIs

proto/spaceone/api/inventory/v1/cloud_service.proto
- remove `project_group_id` filter
=> feat: remove project_group_id filter

proto/spaceone/api/identity/v2/workspace_user.proto
=> fix: fix wrong rest url

proto/spaceone/api/identity/v2/domain.proto
- add config field to DomainAuthInfo
=> feat: add config field to DomainAuthInfo

proto/spaceone/api/core/v2/query.proto, proto/spaceone/api/statistics/v1/resource.proto
=> refactor: change sort field type

proto/spaceone/api/secret/v1/secret.proto, proto/spaceone/api/secret/v1/trusted_secret.proto, proto/spaceone/api/secret/v1/user_secret.proto
- add user secret APIs
- change api docs
=> feat: add user secret APIs

proto/spaceone/api/monitoring/v1/alert.proto
=> feat: add reset_description field in UpdateAlertRequest

proto/spaceone/api/inventory/v1/change_history.proto
- remove fields in change history API
=> feat: remove fields in change history API

proto/spaceone/api/identity/v2/user_profile.proto
- Modify reset_password request message to UserPasswordResetRequest
=> Modify reset_password request message to UserPasswordResetRequest

proto/spaceone/api/inventory/v1/cloud_service_stats.proto
- change field name in cloud service stats
=> feat: change field name in cloud service stats

proto/spaceone/api/identity/v2/user.proto
- modify parameter name actions -> required_actions
=> Modify parameter name actions -> required_actions

proto/spaceone/api/identity/v2/app.proto
- change field names in identity.App
=> feat: change field names in identity.App

proto/spaceone/api/identity/plugin/external_auth.proto
- add metadata field at AuthorizeRequest
=> Add metadata field at AuthorizeRequest

proto/spaceone/api/identity/v2/workspace_user.proto
- add workspace_id field at WorkspaceUserRequest
=> Add workspace_id field at WorkspaceUserRequest

proto/spaceone/api/identity/v2/workspace_user.proto
- change require parameters in WorkspaceUser API
=> feat: change require parameters in WorkspaceUser API

proto/spaceone/api/identity/v2/app.proto
- add last_access_at for AppInfo
=> Add last_access_at for AppInfo

proto/spaceone/api/cost_analysis/v1/cost_query_set.proto
- add workspace_id for CostQuerySetInfo at CostAnalysis
=> Add workspace_id for CostQuerySetInfo at CostAnalysis

proto/spaceone/api/notification/v1/user_channel.proto
- modify user_channel field secret_id -> user_secret_id
=> Modify user_channel field secret_id -> user_secret_id

proto/spaceone/api/identity/v2/workspace_user.proto
- add workspace_id field at WorkspaceUserFindRequest
=> Add workspace_id field at WorkspaceUserFindRequest

proto/spaceone/api/repository/v1/plugin.proto
- remove repository field at repository.Plugin info
=> Remove repository field at repository.Plugin info

proto/spaceone/api/repository/v1/plugin.proto
=> Recover repository field at repository.Plugin info

proto/spaceone/api/plugin/v1/supervisor.proto, proto/spaceone/api/repository/v1/plugin.proto
- change rest api configuration
=> refactor: change rest api configuration

proto/spaceone/api/identity/v2/token.proto
=> Add auth_type MFA to IssueTokenRequest

proto/spaceone/api/statistics/v1/history.proto, proto/spaceone/api/statistics/v1/schedule.proto
=> feat: revert statistics APIs

proto/spaceone/api/statistics/v1/schedule.proto
=> refactor: remove unused field

proto/spaceone/api/statistics/v1/history.proto, proto/spaceone/api/statistics/v1/schedule.proto
=> fix: change wrong query version

proto/spaceone/api/statistics/v1/history.proto, proto/spaceone/api/statistics/v1/schedule.proto
=> fix: fix wrong query version

proto/spaceone/api/inventory/v1/job.proto
- change fields in inventory.Job
=> feat: change fields in inventory.Job

proto/spaceone/api/cost_analysis/v1/cost.proto, proto/spaceone/api/identity/v2/project.proto, proto/spaceone/api/inventory/v1/cloud_service.proto
- add `project_group_id` filter
=> feat: add project_group_id filter

proto/spaceone/api/identity/v2/domain.proto
- add reset password option when domain create
=> Add reset password option when domain create

proto/spaceone/api/repository/v1/plugin.proto
=> Add PublicRegistryType 'GITHUB'

proto/spaceone/api/cost_analysis/v1/cost_report.proto, proto/spaceone/api/cost_analysis/v1/cost_report_data.proto
Add cost report and cost report data
=> Add cost report and cost report data

proto/spaceone/api/cost_analysis/v1/cost_report.proto, proto/spaceone/api/cost_analysis/v1/cost_report_data.proto
=> Add go package

proto/spaceone/api/cost_analysis/v1/cost_report.proto, proto/spaceone/api/cost_analysis/v1/cost_report_config.proto, proto/spaceone/api/cost_analysis/v1/cost_report_data.proto
=> Add CostReportConfig apis

proto/spaceone/api/inventory/plugin/collector.proto
* Add SKIP status in ResourceInfo when collecting resources by collector
=> Add SKIP status in ResourceInfo when collecting resources by collector

proto/spaceone/api/cost_analysis/v1/cost_report.proto, proto/spaceone/api/cost_analysis/v1/cost_report_config.proto, proto/spaceone/api/cost_analysis/v1/cost_report_data.proto
- modify cost_report, cost_report_config and cost_report_data proto files
=> Modify cost_report, cost_report_config and cost_report_data proto files

proto/spaceone/api/cost_analysis/v1/cost_report.proto, proto/spaceone/api/cost_analysis/v1/cost_report_data.proto
- remove 'created_at' field from cost_report_data
=> Remove 'created_at' field from cost_report_data

proto/spaceone/api/cost_analysis/v1/cost_report_data.proto
=> Add is_confirmed parameter at cost_report_data analyze api

proto/spaceone/api/cost_analysis/v1/cost_report.proto
Add `currency_date` field at cost_report.proto
=> Add `currency_date` field at cost_report.proto

proto/spaceone/api/identity/v2/token.proto
- add permissions and grant_type for temp token
=> Add permissions and grant_type for temp token

proto/spaceone/api/file_manager/v1/file.proto
- add `PROJECT` enum field for CreateFileRequest at file.proto
=> Add `PROJECT` enum field for CreateFileRequest at file.proto

proto/spaceone/api/cost_analysis/v1/cost.proto
=> Add 'data' field at CostInfo

proto/spaceone/api/monitoring/v1/event_rule.proto
- add more actions to EventRule API
=> feat: add more actions to EventRule API

proto/spaceone/api/monitoring/v1/event_rule.proto
=> feat: rollback event rule actions

proto/spaceone/api/identity/v2/user.proto, proto/spaceone/api/search/v1/resource.proto
- add resource.proto for Search Service
=> Add resource.proto for Search Service

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto
* Add display_info variable in dashboard service
=> Add display_info variable in dashboard service

proto/spaceone/api/identity/plugin/account_collector.proto, proto/spaceone/api/identity/v2/job.proto, proto/spaceone/api/identity/v2/provider.proto, proto/spaceone/api/identity/v2/schema.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/identity/v2/user.proto
- add new Resource of identity for service account auto sync
=> Add new Resource of identity for service account auto sync

proto/spaceone/api/search/v1/resource.proto
=> Add description field at ResourceInfo

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto
* Add additional variables in dashboard service
=> Add additional variables in dashboard service

proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/secret/v1/trusted_secret.proto
- modify trusted account sync api response
=> Modify trusted account sync api response

proto/spaceone/api/search/v1/resource.proto
- add tags field at ResourceResponse
=> Add tags field at ResourceResponse

proto/spaceone/api/identity/v2/provider.proto
- add update_plugin api for Provider
=> Add update_plugin api for Provider

proto/spaceone/api/secret/v1/trusted_secret.proto
=> Add get_data api for TrustedSecret

proto/spaceone/api/identity/plugin/account_collector.proto
=> Fix AccountInfo field type of identity plugin 'str' -> 'dict'

proto/spaceone/api/identity/v2/role.proto
- Add 'state' field for identity.Role
=> Add 'state' field for identity.Role

proto/spaceone/api/identity/v2/service_account.proto
Chane the return type from `spaceone.api.identity.v2.app.AppInfo` to `AppInfo` for simplicity
=> Change Return Type

proto/spaceone/api/identity/v2/job.proto, proto/spaceone/api/identity/v2/trusted_account.proto, proto/spaceone/api/identity/v2/user_profile.proto
- add 'error_message' at JobInfo of identity
=> Add 'error_message' at JobInfo of identity

proto/spaceone/api/identity/plugin/account_collector.proto, proto/spaceone/api/identity/v2/project.proto, proto/spaceone/api/identity/v2/project_group.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/workspace.proto
=> Add 'reference_id', 'is_managed and' 'last_synced_at' fields 

proto/spaceone/api/identity/plugin/account_collector.proto
- add 'resource_id' at Account Collector Response
=> Add 'resource_id' at Account Collector Response

proto/spaceone/api/identity/v2/user_profile.proto
- add MyWorkspaceInfo at UserProfile
=> Add MyWorkspaceInfo at UserProfile

proto/spaceone/api/identity/v2/job.proto, proto/spaceone/api/identity/v2/provider.proto, proto/spaceone/api/identity/v2/trusted_account.proto
- add plugin_options for trusted service account
=> Add plugin_options for trusted service account

proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/user_profile.proto
- Temporary changed field order
=> Temporary changed field order

proto/spaceone/api/identity/v2/app.proto
- temporary changed field order at AppInfo
=> Temporary changed field order at AppInfo

proto/spaceone/api/identity/v2/app.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/user_profile.proto
=> Recover proto field order for user_profile, service_account, app

proto/spaceone/api/identity/v2/user_profile.proto
- add role_name field at MyWorkspaceInfo
=> Add role_name field at MyWorkspaceInfo

proto/spaceone/api/identity/v2/project.proto, proto/spaceone/api/identity/v2/project_group.proto, proto/spaceone/api/identity/v2/workspace.proto
=> Add trusted_account_id field at project, project_group, workspace info

proto/spaceone/api/inventory/v1/metric.proto, proto/spaceone/api/inventory/v1/metric_data.proto, proto/spaceone/api/inventory/v1/namespace.proto
- add `Namespace` APIs
- add `Metric` APIs
- add `MetricData` APIs
=> feat: add metric APIs

proto/spaceone/api/inventory/v1/metric_data.proto
- add request message in metric_data.proto
=> feat: add request message in metric_data.proto

proto/spaceone/api/inventory/v1/metric.proto, proto/spaceone/api/inventory/v1/namespace.proto
- change message in metric APIs
- change message in namespace APIs
=> feat: change message in metric and namespace APIs

proto/spaceone/api/inventory/v1/metric.proto, proto/spaceone/api/inventory/v1/namespace.proto
=> feat: remove category field

proto/spaceone/api/identity/v2/agent.proto, proto/spaceone/api/identity/v2/service_account.proto
I wrote and modified the code to manage the App CRUD, which was previously managed from the Service Account, through a new resource called 'Agent'.
=> Add Agent resource and modify Service Account resource

proto/spaceone/api/cost_analysis/plugin/cost.proto
- modify cost field type 'float' -> 'double' for cost plugin
=> Modify cost field type 'float' -> 'double' for cost plugin

proto/spaceone/api/identity/v2/agent.proto
=> Reorder protobuf

proto/spaceone/api/identity/v2/agent.proto
=> Add agent_id protobuf

proto/spaceone/api/inventory/v1/metric.proto
- add `run` API to `inventory.Metric`
- add `test` API to `inventory.Metric`
=> feat: add run and test APIs to inventory.Metric

proto/spaceone/api/identity/v2/app.proto, proto/spaceone/api/identity/v2/service_account.proto
Remove service_account_id filed at AppInfo
=> Remove service_account_id filed at AppInfo

proto/spaceone/api/identity/v2/agent.proto
=> Remove tags field

proto/spaceone/api/identity/v2/agent.proto
=> Delete name field in agent

proto/spaceone/api/inventory/v1/metric.proto
- add `query_options` to Metric.test API
=> feat: add query_options field to Metric.test API

proto/spaceone/api/identity/v2/workspace.proto
=> Add delete workspace force option

proto/spaceone/api/inventory/v1/metric.proto
=> feat: add date_field to Metric

proto/spaceone/api/cost_analysis/v1/data_source.proto
- Add update secret data api for DataSource
=> Add update secret data api for DataSource

proto/spaceone/api/cost_analysis/plugin/cost.proto
- add cost-analysis Cost get_linked_accounts api
=> Add cost-analysis Cost pluin `get_linked_accounts` api

proto/spaceone/api/cost_analysis/plugin/cost.proto, proto/spaceone/api/cost_analysis/plugin/job.proto, proto/spaceone/api/cost_analysis/v1/data_source_account.proto
- add DataSourceAccount service
=> Add DataSourceAccount service

proto/spaceone/api/identity/v2/workspace.proto
- modify reference_id field type at WorkspaceInfo 'string' -> 'list'
=> Modify reference_id field type at WorkspaceInfo 'string' -> 'list'

proto/spaceone/api/inventory/v1/metric_example.proto
- change field option
- add workspace_id field
=> Change MetricExample Message

proto/spaceone/api/inventory/v1/metric_example.proto
- add namespace_id field to MetricExample
=> feat: add namespace_id filed to MetricExample

proto/spaceone/api/cost_analysis/v1/data_source_account.proto
=> Remove unused field at data_source_account.proto

proto/spaceone/api/cost_analysis/v1/data_source.proto
- add connected_workspace_id at DataSourceQuery message
=> Add connected_workspace_id at DataSourceQuery message

proto/spaceone/api/core/v2/query.proto
- change type of `group_by` field
=> refactor: change type of group_by field

proto/spaceone/api/inventory/v1/metric.proto
- change type of label_keys in Metric
=> feat: change type of label_keys

proto/spaceone/api/cost_analysis/v1/data_source_account.proto
- modify response at cost_analysis.DataSourceAccount reset api to empty
=> Modify response at cost_analysis.DataSourceAccount reset api to empty

proto/spaceone/api/cost_analysis/v1/data_source_rule.proto
- add all_workspaces field at DataSourceRule Actions
=> Add all_workspaces field at DataSourceRule Actions

proto/spaceone/api/cost_analysis/v1/data_source_account.proto
- add analyze api for DataSourceAccount
=> Add analyze api for DataSourceAccount

proto/spaceone/api/inventory/v1/metric.proto
- change field name in inventory.Metric
=> feat: change field name

proto/spaceone/api/inventory/v1/cloud_service.proto
- change collection_info field type
=> feat: change collection_info field type

proto/spaceone/api/config/v1/workspace_config.proto
- add WorkspaceConfig at Config service
=> Add WorkspaceConfig at Config service

proto/spaceone/api/inventory/v1/metric_data.proto
- change message of `MetricDataInfo`
=> feat: change message of MetricDataInfo

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/private_data_table.proto, proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto, proto/spaceone/api/dashboard/v1/public_data_table.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
- change dashboard fields
- remove dashboard version APIs
- add widget APIs
- add data table APIs
=> Improvement Dashboard APIs

proto/spaceone/api/cost_analysis/v1/data_source_account.proto
- add `is_linked` field at DataSourceAccountInfo
=> Add `is_linked` field at DataSourceAccountInfo

proto/spaceone/api/inventory/v1/metric.proto, proto/spaceone/api/inventory/v1/namespace.proto
- change metric and namespace fields
=> feat: change metric and namespace fields

proto/spaceone/api/inventory/v1/metric_example.proto
=> feat: remove workspace_id field

proto/spaceone/api/inventory/v1/metric.proto, proto/spaceone/api/inventory/v1/namespace.proto
- change namespace fields
- change metric field options
=> feat: change namespace and metric fields

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/private_data_table.proto, proto/spaceone/api/dashboard/v1/private_folder.proto, proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto, proto/spaceone/api/dashboard/v1/public_data_table.proto, proto/spaceone/api/dashboard/v1/public_folder.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
=> feat: change new dashboard APIs

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/private_folder.proto
- add workspace_id field to PrivateFolder
- add workspace_id field to PrivateDashboard
=> feat: add workspace_id field to PrivateFolder and PrivateDashboard

proto/spaceone/api/dashboard/v1/private_data_table.proto, proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_data_table.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
- change message in dashboard service
- change field description in dashboard service
=> Change Dashboard Messages

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto
- change field type in dashboard service
=> feat: change field type

proto/spaceone/api/dashboard/v1/public_data_table.proto
- add filter option
- add filter_or option
=> feat: add filter option

proto/spaceone/api/dashboard/v1/public_data_table.proto
- change field type in dashboard service
=> feat: change field type in dashboard service

proto/spaceone/api/dashboard/v1/public_data_table.proto
- change message in dashboard service
=> feat: change message in dashboard service

proto/spaceone/api/core/v2/query.proto, proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
- add unwind option to analyze query
- add data_table_id field to dashboard widget
=> Change Widget Message and Query Option

proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
=> feat: change widget field

proto/spaceone/api/config/v1/public_config.proto
- add new Resource at Config service 'PublicConfig'
=> Add new Resource at Config service 'PublicConfig'

proto/spaceone/api/config/v1/public_config.proto
- modify request field at PublicConfig resource
=> Modify request field at PublicConfig resource

proto/spaceone/api/cost_analysis/v1/cost_report.proto, proto/spaceone/api/cost_analysis/v1/data_source.proto
- add update_permissions api at data_source.proto
=> Add update_permissions api at data_source.proto

proto/spaceone/api/cost_analysis/v1/cost_report_data.proto
- add project_id field at CostReportDataAnalyzeQuery request
=> Add project_id field at CostReportDataAnalyzeQuery request

proto/spaceone/api/board/v1/post.proto
- change post messages in board service
=> feat: change post messages in board service

proto/spaceone/api/cost_analysis/v1/cost_report_data.proto
- add cost_report_id field at CostReportDataAnalyzeQuery request
=> Add cost_report_id field at CostReportDataAnalyzeQuery request

proto/spaceone/api/board/v1/post.proto
=> feat: change enum field

proto/spaceone/api/dashboard/v1/public_data_table.proto
- change transform options in data table
=> feat: change transform options in data table

proto/spaceone/api/dashboard/v1/public_data_table.proto
=> feat: change enum values

proto/spaceone/api/repository/v1/dashboard_template.proto, proto/spaceone/api/repository/v1/plugin.proto
=> feat: add dashboard template APIs

proto/spaceone/api/dashboard/v1/public_dashboard.proto, proto/spaceone/api/dashboard/v1/public_folder.proto
- implement dashboard sharing feature
=> feat: implement dashboard sharing feature

proto/spaceone/api/dashboard/v1/public_dashboard.proto, proto/spaceone/api/dashboard/v1/public_folder.proto
=> refactor: change shared options

proto/spaceone/api/dashboard/v1/public_data_table.proto
=> feat: change data table options

proto/spaceone/api/dashboard/v1/public_data_table.proto
=> feat: change oneof field name

proto/spaceone/api/dashboard/v1/public_data_table.proto
=> feat: change cost source message

proto/spaceone/api/identity/v2/workspace_user.proto
- add email_verified filed at WorkspaceUsersInfo
=> Add email_verified filed at WorkspaceUsersInfo

proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
- add `state` to public widget
- add `state` to private widget
=> feat: add state to widget

proto/spaceone/api/identity/v2/project.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/user_profile.proto, proto/spaceone/api/identity/v2/workspace.proto, proto/spaceone/api/secret/v1/secret.proto
- add APIs for dormant features
- remove user_group field in project
=> Add APIs for Dormant Features

Dockerfile
=> build: change dockerfile

proto/spaceone/api/identity/v2/service_account.proto
- add field to service account info
=> feat: add field to service account info

proto/spaceone/api/monitoring/v1/alert.proto
- change message in monitoring service
=> feat: change message in monitoring service

proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
- add `data_tables` field to widget for cloning widget
=> feat: add data_tables field to widget for cloning widget

proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
- add `data_table_id` field for cloning widget
=> feat: add data_table_id field to widget for cloning widget

proto/spaceone/api/monitoring/plugin/event.proto, proto/spaceone/api/monitoring/v1/alert.proto, proto/spaceone/api/monitoring/v1/escalation_policy.proto, proto/spaceone/api/monitoring/v1/event.proto, proto/spaceone/api/monitoring/v1/webhook.proto, proto/spaceone/api/notification/v1/notification.proto
- expand notification level
- change alert messages
- change event messages
- add requests field to webhook
=> Refactor Alert Manager

proto/spaceone/api/monitoring/v1/event.proto
- change field in monitoring event
=> feat: change field in monitoring event

proto/spaceone/api/identity/v2/workspace_group.proto
Update users from a list of strings to a list of dictionaries
=> Update users from list of string to list of dictionary

proto/spaceone/api/identity/v2/workspace_group.proto
=> Update user info

proto/spaceone/api/identity/v2/workspace_group.proto
=> Update user group request

proto/spaceone/api/identity/v2/workspace_group.proto
This is an API that allows you to search for all users in a domain, excluding the users already present in the current `workspace_group_id`.
=> Add workspace_group find API

proto/spaceone/api/identity/v2/role_binding.proto
Add workspace_group_id to the role binding
=> Add workspace_group_id to the role binding

proto/spaceone/api/identity/v2/workspace_group_details.proto
Modify get_workspace_groups endpoint
=> Modify get_workspace_groups endpoint

proto/spaceone/api/identity/v2/workspace_group.proto
Add role_binding_info to WorkspaceGroupInfo
=> Add role_binding_info to WorkspaceGroupInfo

proto/spaceone/api/identity/v2/workspace_group.proto
Modify RoleBindingInfo in workspace group
=> Modify RoleBindingInfo in workspace group

proto/spaceone/api/identity/v2/workspace_group.proto
Update role_binding_info to workspace group user
=> Update role_binding_info to workspace group user

proto/spaceone/api/identity/v2/workspace_group_user.proto
Add workspace_group_id for stat api
=> Add workspace_group_id for stat api

proto/spaceone/api/identity/v2/user_profile.proto
Add my workspace group info API
=> Add my workspace group info API

proto/spaceone/api/identity/v2/user_profile.proto
=> Update import path

proto/spaceone/api/identity/v2/workspace_group_user.proto
Add params_user_id because of injected params
=> Add params_user_id because of injected params

proto/spaceone/api/identity/v2/workspace_group_user.proto
=> Modify variable name

proto/spaceone/api/identity/v2/role.proto
Add domain_id, created_at, updated_at to BasicRoleInfo
=> Add domain_id, created_at, updated_at to BasicRoleInfo

proto/spaceone/api/identity/v2/token.proto
- add page access field at identity.GrantTokenInfo
=> Add page access field at identity.GrantTokenInfo

proto/spaceone/api/cost_analysis/plugin/job.proto
- add `name` field at cost-analysis plugin at SyncedAccountInfo
=> Add `name` field at cost-analysis plugin at SyncedAccountInfo

proto/spaceone/api/dashboard/v1/public_data_table.proto
- change data type of expressions in EvaluateOperator
=> feat: change data type of expressions in EvaluateOperator

proto/spaceone/api/cost_analysis/v1/data_source_rule.proto
- add 'match_workspace' rule at DataSourceRuleActions
=> Add 'match_workspace' rule at DataSourceRuleActions

proto/spaceone/api/inventory/v1/collector_rule.proto
- fix type at collector rule request url(list, stat)
=> Fix type at collector rule request url(list, stat)

proto/spaceone/api/identity/v2/workspace_user.proto
Rollback role_binding_info to dictionary in workspace user
=> Rollback role_binding_info to dictionary in workspace user

proto/spaceone/api/identity/v2/workspace.proto, proto/spaceone/api/identity/v2/workspace_group.proto
Update workspace and workspace group user
=> Update workspace and workspace group user

proto/spaceone/api/identity/v2/workspace_group_user.proto
Remove workspaces of workspace_group_user_info
=> Remove workspaces of workspace_group_user_info

proto/spaceone/api/identity/v2/workspace_group.proto, proto/spaceone/api/identity/v2/workspace_group_user.proto
=> Remove redundancy

proto/spaceone/api/identity/v2/workspace_group.proto
Add workspace_count field to workspace_group
=> Add workspace_count field to workspace_group

proto/spaceone/api/identity/v2/workspace.proto
Add changed_at to WorkspaceInfo
=> Add changed_at to WorkspaceInfo

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto
- Add change folder api for public and private dashboard
=> Add change folder api for public and private dashboard

proto/spaceone/api/identity/v2/token.proto
- Remove page_access field at GrantTokenInfo
=> Remove page_access field at GrantTokenInfo

proto/spaceone/api/cost_analysis/v1/unified_cost.proto
- add new feature 'UnifiedCost' for Cost service
=> Add new feature 'UnifiedCost' for Cost service

proto/spaceone/api/dashboard/v1/public_dashboard.proto, proto/spaceone/api/dashboard/v1/public_folder.proto
- add feature to share dashboard folder
=> feat: add feature to share dashboard folder

proto/spaceone/api/dashboard/v1/public_folder.proto
- add missing message to PublicFolder
=> fix: add missing message to PublicFolder

proto/spaceone/api/dashboard/v1/public_dashboard.proto, proto/spaceone/api/dashboard/v1/public_folder.proto
=> fix: fix duplicate enum field

proto/spaceone/api/inventory/v1/cloud_service.proto
- add description of cloud service response model at inventory.CloudService
=> Add description of cloud service response model at inventory.CloudService 

proto/spaceone/api/cost_analysis/v1/unified_cost.proto
- Add description for `UnifiedCost` Service
=> Add description for `UnifiedCost` Service

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto
- add `vars_schema` field to dashboard
=> feat: add field to dashboard

proto/spaceone/api/identity/v2/user.proto, proto/spaceone/api/identity/v2/user_profile.proto
- Add set refresh timeout method for domain admin role type user
=> Add set refresh timeout method for domain admin role type user

proto/spaceone/api/mzc_service_api/v1/contract.proto, proto/spaceone/api/mzc_service_api/v1/offering.proto, proto/spaceone/api/mzc_service_api/v1/organization.proto
- initial commit for mzc service api
=> feat: initial commit for mzc service api

proto/spaceone/api/dashboard/v1/private_data_table.proto, proto/spaceone/api/dashboard/v1/public_data_table.proto
* Add vars field in DataTable resources
=> Add vars field in DataTable resources

proto/spaceone/api/identity/v2/external_auth.proto, proto/spaceone/api/identity/v2/job.proto, proto/spaceone/api/identity/v2/project_group.proto, proto/spaceone/api/identity/v2/token.proto, proto/spaceone/api/identity/v2/workspace_user.proto
- Add examples for identity
- external_auth, token, workspace_user, job, project group
=> Add examples for identity

proto/spaceone/api/workflow/task_category.proto
- initial commit for workflow service
=> feat: initial commit for workflow service

proto/spaceone/api/identity/v2/role_binding.proto, proto/spaceone/api/identity/v2/service_account.proto, proto/spaceone/api/identity/v2/trusted_account.proto
- Add examples for identity
- role_binding, service_account, trusted_account
=> Add examples for role_binding, service_account, trusted_account

proto/spaceone/api/opsflow/comment.proto, proto/spaceone/api/opsflow/event.proto, proto/spaceone/api/opsflow/task.proto, proto/spaceone/api/opsflow/task_category.proto, proto/spaceone/api/opsflow/task_type.proto
=> fix: typo in task.proto

proto/spaceone/api/opsflow/v1/task.proto, proto/spaceone/api/opsflow/v1/task_category.proto, proto/spaceone/api/opsflow/v1/task_type.proto
- add assignee_pool field to task_type
=> feat: add assignee_pool field to task_type

proto/spaceone/api/identity/v2/workspace.proto
- add package management APIs to Workspace
=> feat: add package management APIs to Workspace

proto/spaceone/api/core/v2/query.proto
- change unwind option in analyze query
=> feat: change unwind option in analyze query

.github/workflows/dispatch_release.yaml
=> Add release workflow

proto/spaceone/api/identity/v2/agent.proto, proto/spaceone/api/identity/v2/endpoint.proto, proto/spaceone/api/inventory_v2/v1/collector.proto, proto/spaceone/api/inventory_v2/v1/job.proto, proto/spaceone/api/inventory_v2/v1/job_task.proto
Add collector service at inventory-v2
=> Add collector service at inventory-v2

proto/spaceone/api/inventory_v2/v1/collector.proto
- fix type and remove 'capability' field at collector response
=> Fix type and remove 'capability' field at collector response

proto/spaceone/api/alert_manager/v1/alert.proto, proto/spaceone/api/alert_manager/v1/escalation_policy.proto, proto/spaceone/api/alert_manager/v1/event.proto, proto/spaceone/api/alert_manager/v1/event_rule.proto, proto/spaceone/api/alert_manager/v1/note.proto, proto/spaceone/api/alert_manager/v1/notification_protocol.proto, proto/spaceone/api/alert_manager/v1/plugin/event.proto, proto/spaceone/api/alert_manager/v1/plugin/webhook.proto, proto/spaceone/api/alert_manager/v1/service.proto, proto/spaceone/api/alert_manager/v1/service_channel.proto, proto/spaceone/api/alert_manager/v1/user_channel.proto, proto/spaceone/api/alert_manager/v1/user_group_channel.proto, proto/spaceone/api/alert_manager/v1/webhook.proto
=> add: add Alert Manager proto

proto/spaceone/api/inventory_v2/v1/metric.proto, proto/spaceone/api/inventory_v2/v1/metric_data.proto, proto/spaceone/api/inventory_v2/v1/metric_example.proto
- Add metric, metric_data, metric_example at inventory v2
=> Add metric, metric_data, metric_example

proto/spaceone/api/alert_manager/v1/notification_protocol.proto
- modify duplicated http api for change-member
=> Modify duplicated http api for change-member

proto/spaceone/api/alert_manager/v1/alert.proto, proto/spaceone/api/alert_manager/v1/event.proto, proto/spaceone/api/alert_manager/v1/event_rule.proto, proto/spaceone/api/alert_manager/v1/note.proto, proto/spaceone/api/alert_manager/v1/plugin/event.proto, proto/spaceone/api/alert_manager/v1/plugin/webhook.proto, proto/spaceone/api/alert_manager/v1/service_channel.proto, proto/spaceone/api/alert_manager/v1/user_channel.proto, proto/spaceone/api/alert_manager/v1/user_group_channel.proto
- remove all duplicate http api
=> Remove all duplicate http api at alert manager

proto/spaceone/api/opsflow/v1/event.proto
- [x] Bug fix
- add missing field
=> fix: add missing field

proto/spaceone/api/identity/v2/service_account.proto
feat: add identity service_Account analyze.
=> Add identity service_Account analyze.

proto/spaceone/api/opsflow/v1/task_type.proto
- add include_category_fields parameter
=> fix: add include_category_fields parameter

proto/spaceone/api/opsflow/v1/comment.proto, proto/spaceone/api/opsflow/v1/task.proto
=> fix: add created_by parameter

proto/spaceone/api/inventory_v2/v1/collector.proto, template/python/setup.py.tmpl
- Add created_by field at collector info of inventory v2
=> Add created_by field at collector info of inventory v2

proto/spaceone/api/alert_manager/v1/escalation_policy.proto
fix: fix escalation_policy.proto repeat field
=> fix: fix escalation_policy.proto repeat field

proto/spaceone/api/alert_manager/v1/service_channel.proto
- change schedule type in alert manager
=> feat: change schedule type in alert manager

proto/spaceone/api/alert_manager/v1/event_rule.proto, proto/spaceone/api/alert_manager/v1/notification_protocol.proto, proto/spaceone/api/alert_manager/v1/service_channel.proto, proto/spaceone/api/alert_manager/v1/user_channel.proto, proto/spaceone/api/alert_manager/v1/user_group_channel.proto
- change messages in alert manager
=> feat: change messages in alert manager

proto/spaceone/api/alert_manager/v1/service.proto
=> feat: change duplicated message in alert manager

proto/spaceone/api/inventory_v2/v1/collector.proto, proto/spaceone/api/inventory_v2/v1/job.proto
- add examples for inventory_v2 Job
=> Add examples for inventory_v2 Job

proto/spaceone/api/inventory_v2/v1/job.proto, proto/spaceone/api/inventory_v2/v1/job_task.proto
- add JobTask api interface for inventory v2
=> Add JobTask api interface for inventory v2

proto/spaceone/api/dashboard/v1/public_data_table.proto
* Add Operators in transform method of DataTable
=> Add Operators in transform method of DataTable

proto/spaceone/api/alert_manager/v1/webhook.proto
=> fix: fix webhook.proto api path

proto/spaceone/api/inventory_v2/v1/region.proto
=> Fix Region api to identity-v2

proto/spaceone/api/dashboard/v1/public_data_table.proto
* change timediff and delete options in AddOptions
=> Change timediff and delete options in AddOptions

proto/spaceone/api/alert_manager/v1/service.proto
=> fix: fix service.proto alert state

proto/spaceone/api/inventory_v2/v1/asset.proto
- add Asset api interface for inventory v2
=> Add Asset api interface for inventory v2

proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
* Add load_sum method in Widget
=> Add load_sum method in Widget

proto/spaceone/api/opsflow/v1/task.proto, proto/spaceone/api/opsflow/v1/task_category.proto
- add state, deleted_at parameter
=> fix: add state, deleted_at parameter

proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
* Change interface of load and load_sum methods
=> Change interface of load and load_sum methods

proto/spaceone/api/dashboard/v1/private_data_table.proto, proto/spaceone/api/dashboard/v1/public_data_table.proto
* Add sort_keys field in DataTable info
=> Add sort_keys field in DataTable info

proto/spaceone/api/identity/v2/user_profile.proto
- add update password api to UserProfile
=> Add update password api to UserProfile

proto/spaceone/api/alert_manager/v1/user_group_channel.proto
add data field in UserGroupChannelInfo
=> fix: add data field in UserGroupChannelInfo

proto/spaceone/api/alert_manager/v1/alert.proto
fix alert info field name triggered_type
=> fix: fix alert info field name triggered_type

proto/spaceone/api/alert_manager/v1/service.proto
add service.alerts RESOLVED field
=> fix: add service.alerts RESOLVED field

proto/spaceone/api/dashboard/v1/private_data_table.proto, proto/spaceone/api/dashboard/v1/private_widget.proto, proto/spaceone/api/dashboard/v1/public_data_table.proto, proto/spaceone/api/dashboard/v1/public_widget.proto
* Add group_by options when loading Widget
=> Add group_by options when loading Widget

proto/spaceone/api/alert_manager/v1/escalation_policy.proto
add escalation_policy repeat fields at update request
=> fix: add escalation_policy repeat fields at update request

proto/spaceone/api/config/v1/domain_config.proto, proto/spaceone/api/config/v1/public_config.proto, proto/spaceone/api/config/v1/shared_config.proto, proto/spaceone/api/config/v1/user_config.proto
=> refactor: refactor config APIs

proto/spaceone/api/config/v1/public_config.proto
=> feat: add field to public config

proto/spaceone/api/alert_manager/v1/service.proto
- add force option to `Service.delete` API
=> feat: add force option to Service.delete API

proto/spaceone/api/alert_manager/v1/service.proto
- change message of Service.delete API
=> feat: change message of Service.delete API

proto/spaceone/api/alert_manager/v1/notification_protocol.proto
- change message of notification protocol
=> refactor: change message of notification protocol

proto/spaceone/api/alert_manager/v1/notification_protocol.proto
- add method to notification protocol
=> feat: add method to notification protocol

proto/spaceone/api/opsflow/v1/comment.proto, proto/spaceone/api/opsflow/v1/event.proto, proto/spaceone/api/opsflow/v1/task_category.proto, proto/spaceone/api/opsflow/v1/task_type.proto
=> fix: add vars, source parameter

proto/spaceone/api/dashboard/v1/private_data_table.proto, proto/spaceone/api/dashboard/v1/public_data_table.proto
* Delete cache_key field in Table info
=> Delete cache_key field in Table info

proto/spaceone/api/opsflow/v1/variable.proto
=> feat: add variable api to opsflow

proto/spaceone/api/opsflow/v1/variable.proto
- remove resource_group parameter
=> fix: remove resource_group parameter

proto/spaceone/api/opsflow/v1/comment.proto, proto/spaceone/api/opsflow/v1/task.proto
- add reference_id parameter to opsflow
=> fix: add reference_id parameter to opsflow

proto/spaceone/api/file_manager/v1/file.proto
=> feat: change file manager apis

proto/spaceone/api/alert_manager/v1/service_channel.proto
=> fix: fix wrong response message

proto/spaceone/api/alert_manager/v1/service.proto
- add details option when get or list services
=> feat: add details option when get or list services

proto/spaceone/api/alert_manager/v1/webhook.proto
- remove method from alert manager webhook
=> feat: remove method from alert manager webhook

proto/spaceone/api/alert_manager/v1/service.proto
- change field name in alert manager
=> feat: change field name in alert manager

proto/spaceone/api/alert_manager/v1/event_rule.proto
- add scope field to event rule
=> feat: add scope field to event rule

proto/spaceone/api/alert_manager/v1/event_rule.proto
- add webhook option to event rule search query
=> feat: add webhook option to event rule search query

proto/spaceone/api/alert_manager/v1/event_rule.proto
- add webhook_id to event rule info
=> feat: add webhook_id to event rule info

proto/spaceone/api/alert_manager/v1/alert.proto
=> feat: change alert messages

proto/spaceone/api/alert_manager/v1/alert.proto, proto/spaceone/api/alert_manager/v1/event.proto
- remove fields from alert
- remove fields from event
=> feat: remove fields from alert and event

proto/spaceone/api/alert_manager/v1/alert.proto
- change alert history request
=> feat: change alert history request

proto/spaceone/api/alert_manager/v1/alert.proto
- add fields to AlertEventInfo
=> feat: add fields to AlertEventInfo

proto/spaceone/api/alert_manager/v1/alert.proto
=> feat: add fields to alert info

proto/spaceone/api/opsflow/v1/comment.proto, proto/spaceone/api/opsflow/v1/event.proto, proto/spaceone/api/opsflow/v1/task.proto, proto/spaceone/api/opsflow/v1/task_category.proto, proto/spaceone/api/opsflow/v1/task_type.proto
- add scope, resource_group parameter to opsflow
=> fix: add scope, resource_group parameter to opsflow

proto/spaceone/api/dashboard/v1/private_data_table.proto, proto/spaceone/api/dashboard/v1/public_data_table.proto
* Delete sort_keys in dashboard
=> Delete sort_keys in dashboard

proto/spaceone/api/opsflow/v1/comment.proto, proto/spaceone/api/opsflow/v1/task.proto, proto/spaceone/api/opsflow/v1/task_type.proto
- remove scope, resource_group parameter to opsflow
=> fix: remove scope, resource_group parameter to opsflow

proto/spaceone/api/dashboard/v1/public_data_table.proto
- change value mapping message in dashboard
=> feat: change value mapping message in dashboard

proto/spaceone/api/alert_manager/v1/alert.proto, proto/spaceone/api/alert_manager/v1/webhook.proto
- change message in alert manager
=> feat: change message in alert manager

proto/spaceone/api/alert_manager/v1/event.proto
- change enum value in event info
=> feat: change enum value in event info

proto/spaceone/api/opsflow/v1/comment.proto, proto/spaceone/api/opsflow/v1/task.proto
- add contents_type field to TaskInfo, CommentInfo
=> feat: add contents_type field to TaskInfo, CommentInfo

proto/spaceone/api/alert_manager/v1/alert.proto
- add duration fields to alert info
=> feat: add duration fields to alert info

proto/spaceone/api/dashboard/v1/public_data_table.proto
* Change data type of group_by field in AggregateOperator
=> Change data type of group_by field in AggregateOperator

proto/spaceone/api/alert_manager/v1/alert.proto
=> feat: change history query option

proto/spaceone/api/alert_manager/v1/service_channel.proto, proto/spaceone/api/alert_manager/v1/user_channel.proto, proto/spaceone/api/alert_manager/v1/user_group_channel.proto
- add plugin_id field to channel_info
=> feat: add plugin_id field to channel info

proto/spaceone/api/alert_manager/v1/event_rule.proto
- change message of event rule
=> feat: change message of event rule

proto/spaceone/api/alert_manager/v1/webhook.proto
=> feat: add api to webhook

proto/spaceone/api/alert_manager/v1/alert.proto
- add option to alert search query
=> feat: add option to alert search query

proto/spaceone/api/alert_manager/v1/alert.proto
=> feat: add an alert action

proto/spaceone/api/identity/v2/user_profile.proto
Remove password field from UserProfile Update
=> Remove password field from UserProfile Update

proto/spaceone/api/cost_analysis/plugin/job.proto, proto/spaceone/api/cost_analysis/v1/job.proto, proto/spaceone/api/cost_analysis/v1/job_task.proto
- add task_changed field at job task info
=> Add task_changed field at job task info

.github/workflows/dispatch_release.yaml
=> Modify release workflow

proto/spaceone/api/cost_analysis/v1/data_source.proto
* delete state filed and verb & add schedule field
=> fix: delete state filed and verb & add schedule field

proto/spaceone/api/dashboard/v1/public_data_table.proto
* Add UnifiedCostSource and update public data table proto
=> Add UnifiedCostSource and update public data table proto

proto/spaceone/api/cost_analysis/v1/unified_cost.proto
- add run method to UnifiedCost service and update proto definitions
=> Add run method to UnifiedCost service and update proto definitions

pkg/pip_requirements.txt
- modify python package version for build
=> Modify python package version for build

proto/spaceone/api/cost_analysis/v1/budget.proto, proto/spaceone/api/cost_analysis/v1/budget_usage.proto
=> Modify budget and budget usages apis

proto/spaceone/api/cost_analysis/v1/budget.proto
- add currency field at budget create api
=> Add currency field at budget create api

proto/spaceone/api/dashboard/v1/private_dashboard.proto, proto/spaceone/api/dashboard/v1/private_folder.proto, proto/spaceone/api/dashboard/v1/public_dashboard.proto, proto/spaceone/api/dashboard/v1/public_folder.proto
* Add project_group_id field to public and private dashboard proto files
=> Add project_group_id field to public and private dashboard proto files

proto/spaceone/api/cost_analysis/v1/budget.proto, proto/spaceone/api/cost_analysis/v1/budget_usage.proto
- modify field name notifications -> notification
=> Modify field name notifications -> notification

proto/spaceone/api/cost_analysis/v1/budget.proto
- add budget_manager_id field at BudgetInfo
=> Add budget_manager_id field at BudgetInfo

proto/spaceone/api/cost_analysis/v1/budget.proto, proto/spaceone/api/cost_analysis/v1/budget_usage.proto
=> Remove data_source_id field at budget and budget_usage at examples

proto/spaceone/api/cost_analysis/v1/budget.proto
- add `budget_manager_notification` field at BudgetInfo
=> Add `budget_manager_notification` field at BudgetInfo

proto/spaceone/api/cost_analysis/v1/budget.proto
- remove 'budget_year' and add 'state' field
=> Remove 'budget_year' and add 'state' field

proto/spaceone/api/alert_manager/v1/alert.proto
add export method for excel download.
=> feat: add export method for excel download.

proto/spaceone/api/cost_analysis/v1/cost_report.proto, proto/spaceone/api/cost_analysis/v1/report_adjustment_policy.proto
=> Add DONE state and update project_id/workspace_id fields to repeated in cost_report and report_adjustment_policy proto files

proto/spaceone/api/identity/v2/workspace_user.proto
- add auth_type field to workspace_user.proto for user authentication
=> Add auth_type field to workspace_user.proto for user authentication

proto/spaceone/api/repository/v1/plugin.proto
- [o] New feature
- repostoty added ( gcp artifact repository )
=> feat: GCP_PRIVATE_GCR 추가(Plugin)

proto/spaceone/api/cost_analysis/v1/cost_report_config.proto
* add optional send_report field to CostReportConfigRequest
=> fix: add optional send_report field to CostReportConfigRequest

proto/spaceone/api/identity/v2/service_account.proto
* add optional has_secret field to service account
=> fix: add optional has_secret field to service account
