cloudforet-io/api

proto/spaceone/api/identity/v1/service_account.proto
feat: Add service_account_type, trusted_service_account_id for Identity service
Add service_account_type to ServiceAccount API ([#4](https://github.com/cloudforet-io/identity/issues/4))
=> feat: Add service_account_type, trusted_service_account_id for Identity service

proto/spaceone/api/monitoring/v1/escalation_policy.proto
* Change the scope field from GLOBAL to DOMAIN in escalation_policy of monitoring service
=> Change the scope field from GLOBAL to DOMAIN in escalation_policy of monitoring service

proto/spaceone/api/repository/v2/provider.proto, proto/spaceone/api/repository/v2/remote_repository.proto
- Some message fields has been updated
- Reference_url has been renamed to reference(also, data type has been changed to struct)
- ProviderQuery had wrong field(sync_option), it has been changed to sync_mode
- Unnecessary field  in RemoteRepositoryQuery has been deleted
- Repository resources do not have a stat verb.
- And providerStatQuery message has been deleted
*) Refer to our api docs.
=> feat: Update protobuf  messages for repo_v2

proto/spaceone/api/file_manager/v1/file.proto
- modify `file-manager` service http request url at proto file
In order to generate GO code this is must be declared in `.proto` file. Here is official [documentation](https://protobuf.dev/reference/go/go-generated/#package) for this
=> Modify file_manager service http request url at proto file

proto/spaceone/api/repository/v1/plugin.proto, proto/spaceone/api/repository/v1/policy.proto, proto/spaceone/api/repository/v1/repository.proto, proto/spaceone/api/repository/v1/schema.proto
- modify`repository` service http request url at proto file
=> Modify repository service http request url at proto file

proto/spaceone/api/secret/v1/secret.proto, proto/spaceone/api/secret/v1/secret_group.proto, proto/spaceone/api/secret/v1/trusted_secret.proto
- modify `secret` service http request url at proto file
=> Modify secret service http request url at proto file

proto/spaceone/api/board/v1/board.proto, proto/spaceone/api/board/v1/post.proto
- modify `board` service http request url at proto file
=> Modify board service http request url at proto file

proto/spaceone/api/monitoring/plugin/data_source.proto, proto/spaceone/api/monitoring/plugin/event.proto, proto/spaceone/api/monitoring/plugin/log.proto, proto/spaceone/api/monitoring/plugin/metric.proto, proto/spaceone/api/monitoring/plugin/webhook.proto, proto/spaceone/api/monitoring/v1/alert.proto, proto/spaceone/api/monitoring/v1/data_source.proto, proto/spaceone/api/monitoring/v1/escalation_policy.proto, proto/spaceone/api/monitoring/v1/event.proto, proto/spaceone/api/monitoring/v1/event_rule.proto, proto/spaceone/api/monitoring/v1/log.proto, proto/spaceone/api/monitoring/v1/maintenance_window.proto, proto/spaceone/api/monitoring/v1/metric.proto, proto/spaceone/api/monitoring/v1/note.proto, proto/spaceone/api/monitoring/v1/project_alert_config.proto, proto/spaceone/api/monitoring/v1/webhook.proto
- modify `monitoring` service http request url at proto file
=> Modify monitoring service http request url at proto file

proto/spaceone/api/repository/v2/provider.proto, proto/spaceone/api/repository/v2/remote_repository.proto
- To more strictly validate gRPC messages, those messages must be declared separately.
- In this PR, `sync_options` and `capability` has been declared separately.
- Unused `import` sentence has been removed
=> feat: fix some field types

proto/spaceone/api/plugin/v1/plugin.proto, proto/spaceone/api/plugin/v1/supervisor.proto
- modify `plugin` service http request url at proto file
=> Modify plugin service http request url at proto file

proto/spaceone/api/cost_analysis/plugin/cost.proto, proto/spaceone/api/cost_analysis/plugin/data_source.proto, proto/spaceone/api/cost_analysis/plugin/job.proto, proto/spaceone/api/cost_analysis/v1/budget.proto, proto/spaceone/api/cost_analysis/v1/budget_usage.proto, proto/spaceone/api/cost_analysis/v1/cost.proto, proto/spaceone/api/cost_analysis/v1/cost_query_set.proto, proto/spaceone/api/cost_analysis/v1/custom_widget.proto, proto/spaceone/api/cost_analysis/v1/data_source.proto, proto/spaceone/api/cost_analysis/v1/data_source_rule.proto, proto/spaceone/api/cost_analysis/v1/exchange_rate.proto, proto/spaceone/api/cost_analysis/v1/job.proto, proto/spaceone/api/cost_analysis/v1/job_task.proto, proto/spaceone/api/cost_analysis/v1/public_dashboard.proto, proto/spaceone/api/cost_analysis/v1/schedule.proto, proto/spaceone/api/cost_analysis/v1/user_dashboard.proto
- modify `cost-analysis` service http request url at proto file
=> Modify cost-analysis service http request url at proto file

proto/spaceone/api/repository/v2/provider.proto
We discussed how to define conditions for service_account in schema fields.
As a result of the discussion, some protobuf messages (schema, description, reference) have been defined separately.
```
schema = [
{
'resource_type': 'value',
'secret_type': 'value', # optional
'schema_id': 'value'
},
...
]
description = [
{
'resource_type': 'value', 
'body': {value}
}
]
reference = [
{
'resource_type': 'value',
'link': {value}
}
]
```
=> feat: define messages separately in provider protobuf

proto/spaceone/api/repository/v2/provider.proto
As a result of discussing the provider resource, we decided to add a 'remote_repository' field to the provider_info.
This PR relates to that decision.
(I didn't create a branch for this because this issue only involves fixing a protobuf message field of the provider resource.)
=> improve: add remote_repository field for provider_info

proto/spaceone/api/config/v1/domain_config.proto, proto/spaceone/api/config/v1/user_config.proto
- modify `config` service http request url at proto file
In order to generate GO code this is must be declared in `.proto` file. Here is official [documentation](https://protobuf.dev/reference/go/go-generated/#package) for this
=> Modify config service http request url at proto file

bin/build.py, bin/openapi.py, pkg/pip_requirements.txt, template/openapi/openapi.json.tmpl
- add openapi target at build.py
- add openapi target and generate openapi.json file based on openapi 3.0 spec
=> Add openapi target at build.py

proto/spaceone/api/identity/v2/role_binding.proto
- change role binding fields in identity v2
=> feat: change role binding fields

proto/spaceone/api/identity/v2/api_key.proto, proto/spaceone/api/identity/v2/app.proto, proto/spaceone/api/identity/v2/user.proto
=> Add App Service

proto/spaceone/api/monitoring/v1/event_rule.proto
=> feat: change event rule actions

proto/spaceone/api/cost_analysis/plugin/job.proto, proto/spaceone/api/cost_analysis/v1/cost.proto, proto/spaceone/api/cost_analysis/v1/data_source_account.proto
- add virtual id field at DataSourceAccount
=> Add virtual id field at DataSourceAccount

proto/spaceone/api/inventory/v1/metric_example.proto, proto/spaceone/api/inventory/v1/namespace.proto
- add MetricExample APIs
- add icon field to Namespace
=> Add MetricExample APIs

proto/spaceone/api/identity/v2/workspace_group_details.proto
I created a Workspace Group Details API that can be accessed with the USER Role Type because a Workspace Group only has DOMAIN_ADMIN, WORKSPACE_OWNER, and WORKSPACE_MEMBER Role Types.
=> Add workspace group details API

proto/spaceone/api/cost_analysis/v1/unified_cost.proto
- add description for `UnifiedCost` Service list api
=> Add description for `UnifiedCost` Service list api 

proto/spaceone/api/cost_analysis/v1/data_source_account.proto
- add field 'reset_sync' at ResetDataSourceAccountRequest
=> Add field 'reset_sync' at ResetDataSourceAccountRequest

proto/spaceone/api/identity/v2/domain.proto, proto/spaceone/api/identity/v2/project.proto, proto/spaceone/api/identity/v2/role.proto, proto/spaceone/api/identity/v2/user.proto, proto/spaceone/api/identity/v2/workspace.proto
- Add examples for identity
- domain, project, role, user, workspace
=> docs: Add examples for domain, project, role, user, workspace

proto/spaceone/api/identity/v2/package.proto
- add package APIs
- change fields of user group APIs
=> feat: add package APIs and change user group APIs

proto/spaceone/api/opsflow/v1/task_category.proto
- add force field to TaskCategoryUpdateRequest message
=> fix: add force field to TaskCategoryUpdateRequest message

proto/spaceone/api/opsflow/v1/task_category.proto, proto/spaceone/api/opsflow/v1/task_type.proto
- add update_fields RPC to TaskType, TaskCategory service
=> fix: add update_fields RPC to TaskType, TaskCategory service

proto/spaceone/api/cost_analysis/v1/data_source.proto
* add schedule to data source request
=> add: add schedule to data source request

proto/spaceone/api/identity/v2/service_account.proto
- add service_account_mgr_id field at ServiceAccountInfo
=> Add service_account_mgr_id field at ServiceAccountInfo

proto/spaceone/api/alert_manager/v1/service.proto
add service_healthy field for pagination.
=> feat: add service_healthy field for pagination.

proto/spaceone/api/cost_analysis/v1/cost_report.proto, proto/spaceone/api/cost_analysis/v1/cost_report_config.proto, proto/spaceone/api/cost_analysis/v1/cost_report_data.proto, proto/spaceone/api/cost_analysis/v1/report_adjustment.proto, proto/spaceone/api/cost_analysis/v1/report_adjustment_policy.proto
=> Add ReportAdjustment and ReportAdjustmentPolicy services with corresponding proto definitions

proto/spaceone/api/alert_manager/v1/alert.proto
add export method fields for excel download.
=> feat: add export method for excel download.

proto/spaceone/api/cost_analysis/v1/cost_report.proto, proto/spaceone/api/cost_analysis/v1/report_adjustment.proto, proto/spaceone/api/cost_analysis/v1/report_adjustment_policy.proto
- feat: update field indices in report adjustment proto files for consistency
=> feat: update field indices in report adjustment proto files for consistency

proto/spaceone/api/cost_analysis/v1/cost_report_config.proto, proto/spaceone/api/cost_analysis/v1/report_adjustment.proto, proto/spaceone/api/cost_analysis/v1/report_adjustment_policy.proto
- add sync_currency api to report_adjustment_policy.proto for currency
=> Add sync_currency api to report_adjustment_policy.proto for currency

proto/spaceone/api/cost_analysis/v1/report_adjustment_policy.proto
- remove scope field when crate report policy
=> Remove scope field when crate report policy

proto/spaceone/api/cost_analysis/v1/report_adjustment.proto
…related comments
- rename PERCENTAGE to PERCENT in AdjustmentUnit enum and update related comments
=> Rename PERCENTAGE to PERCENT in AdjustmentUnit enum and update related comments

proto/spaceone/api/cost_analysis/v1/cost_report.proto
=> Rename workspace_name to name in cost_report.proto for consistency

proto/spaceone/api/cost_analysis/v1/data_source.proto
- add WarehouseInfo message and update data_source.proto for improved structure
=> Add WarehouseInfo message and update data_source.proto for improved structure

proto/spaceone/api/cost_analysis/v1/cost_report.proto
=> fix: enum error from CostReport

proto/spaceone/api/cost_analysis/v1/cost_report_config.proto
* add generate_report RPC to CostReportConfig service
=> fix: add generate_report RPC to CostReportConfig service

proto/spaceone/api/identity/v2/user.proto
feat: Add schema according to MFA enforce option
=> feat: Add schema according to MFA enforce option

proto/spaceone/api/identity/v2/workspace.proto
- [v] New feature
add identity workspace analyze.
=> feat: add identity workspace analyze.

proto/spaceone/api/identity/v2/user.proto
… to flag
The request payload for MFA settings has been changed from the objec to a flag
=> fix: Change user MFA requset payload method from unstructured format to flag
